# -*- coding: utf-8 -*-
"""FireDetection_SaturdayAI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FGRcv6YmvgtFl5BBkSULp-AwLpm40one

# FireDetection using Yolo v5

# Descargamos e instalamos yolov5 con todos sus paquetes.

Clone repo, install dependencies and check PyTorch and GPU.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images download

clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""# 0. No olvidarse de adjuntar el archivo en formato yoloV5. 
Pues si te has olvidado te dejo el [enlace](https://www.youtube.com/watch?v=S0GwVgwjEd0) para que te recuerdes.

# 1. Training the model
En este sección nos enfocamos en entrenar el modelo por defecto con un epoch de 6. Aunque en el ejemplo recomienda 64. Coforme vayamos testeando iremos incrementando el epoch.


`!python train.py --data fire.yaml --cfg yolov5x.yaml --weights '' --batch-size 6`
"""

!python train.py --data fire.yaml --cfg yolov5x.yaml --weights '' --batch-size 16

"""# Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

"""