# -*- coding: utf-8 -*-
"""Prueba WS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lm1KE94k6_siqPfs5vzjJf8cvMs_Y_T5
"""

!pip install requests
!pip install beautifulsoup4
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.comunidadumbria.com/partida/noches-venecianas-2/capitulo-uno-los-sotanos-de-venecia?__Pg=1'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

# Listas para almacenar los datos extraídos
usernames = []
intervenciones = []
dialogos = []
contextos = []
fechas_horas = []
tiradas = []

# Buscar todos los mensajes (intervenciones)
for mensaje_div in soup.find_all('div', class_='mensaje'):
    # Extraer el nombre de usuario
    username_tag = mensaje_div.find(class_='username')
    username = username_tag.text if username_tag else None
    usernames.append(username)

    # Extraer el diálogo dentro de <p><strong></strong></p> en <div class="texto">
    texto_div = mensaje_div.find('div', class_='texto')
    if texto_div:
        p_tag = texto_div.find('p')
        if p_tag:
            strong_tag = p_tag.find('strong')
            dialogo = strong_tag.text if strong_tag else None
        else:
            dialogo = None
    else:
        dialogo = None
    dialogos.append(dialogo)

    # Extraer el contexto dentro de <p> en <div class="texto">
    contexto_tag = texto_div.find('p') if texto_div else None
    contexto = contexto_tag.text if contexto_tag else None
    contextos.append(contexto)

    # Extraer la fecha y hora desde class="fecha"
    fecha_hora_tag = mensaje_div.find(class_='fecha')
    fecha_hora = fecha_hora_tag.text if fecha_hora_tag else None
    fechas_horas.append(fecha_hora)

    # Extraer la tirada desde class="tiradas"
    tirada_tag = mensaje_div.find(class_='tiradas')
    tirada = tirada_tag.text if tirada_tag else None
    tiradas.append(tirada)

# Crear un DataFrame con los datos extraídos
df = pd.DataFrame({
    'Usuario': usernames,
    'Diálogo': dialogos,
    'Contexto': contextos,
    'Fecha_Hora': fechas_horas,
    'Tirada': tiradas
})

# Exportar a CSV
df.to_csv('foro_rol_dataset.csv', index=False)

print(df.head())

from google.colab import drive
drive.mount('/content/drive')

# Ruta de la carpeta en tu Google Drive
folder_path = '/content/drive/My Drive/Colab Notebooks/'

# Guardar el archivo CSV en la carpeta especificada
csv_pruebaws = 'foro_rol_dataset_final.csv'
df.to_csv(folder_path + csv_pruebaws, index=False)

print(f"El archivo CSV se ha guardado correctamente en: {folder_path + csv_pruebaws}")

