API_KEY = 'RGAPI-ff494d20-f42a-4995-9a6e-4e4d33bdf7e8'
REGION = 'euw1'

LIST_FIELDS = ['puuid_current_summoner', 'id_match', 'championName', 'lane', 'perks', 'puuid', 'role', 'summonerId',
               'summonerName', 'teamPosition', 'pk_partida', 'jugador', 'dt_fecha', 'smurf', 'ts_fecha',
               'rango', 'puntuacion_extra', 'championId', 'summoner1Id', 'summoner2Id', 'profileIcon', 'kda', 'item0',
               'item1','item2', 'item3','item4', 'item5', 'item6', 'individualPosition', 'turretsTakenWithRiftHerald',
               'wardTakedowns', 'wardTakedownsBefore20M', 'wardsGuarded', 'champLevel', 'championTransform',
               'damageDealtToTurrets',
               'damageSelfMitigated',
               'unseenRecalls',
               'deaths',
               'doubleKills',
               'dragonKills',
               'eligibleForProgression',
               'firstBloodAssist',
               'firstBloodKill',
               'firstTowerAssist',
               'firstTowerKill',
               'detectorWardsPlaced',
               'twentyMinionsIn3SecondsCount',
               'teleportTakedowns',
               'tookLargeDamageSurvived',
               'soloBaronKills',
               'soloKills',
               'soloTurretsLategame',
               'thirdInhibitorDestroyedTime',
               'survivedSingleDigitHpCount',
               'survivedThreeImmobilizesInFight',
               'takedownOnFirstTurret',
               'takedowns',
               'takedownsAfterGainingLevelAdvantage',
               'takedownsBeforeJungleMinionSpawn',
               'takedownsFirstXMinutes',
               'visionScore',
               'takedownsInEnemyFountain',
               'teamBaronKills',
               'teamElderDragonKills',
               'teamRiftHeraldKills',
               'threeWardsOneSweeperCount',
               'gameEndedInEarlySurrender',
               'goldEarned',
               'goldSpent',
               'inhibitorKills',
               'killsOnLanersEarlyJungleAsJungler',
               'teamEarlySurrendered',
               'teamId',
               'timePlayed',
               'totalDamageDealt',
               'totalDamageDealtToChampions',
               'junglerKillsEarlyJungle',
               'totalDamageTaken',
               'highestCrowdControlScore',
               'controlWardTimeCoverageInRiverOrEnemyHalf',
               'win',
               'totalTimeSpentDead',
               'wardsKilled',
               'tripleKills',
               'trueDamageTaken',
               'turretKills',
               'unrealKills',
               'highestWardKills',
               'snowballsHit',
               'sightWardsBoughtInGame',
               'riotIdName',
               'inhibitorTakedowns',
               'baronBuffGoldAdvantageOverThreshold',
               'killingSprees',
               'kills',
               'largestKillingSpree',
               'largestMultiKill',
               'highestChampionDamage',
               'fastestLegendary',
               'neutralMinionsKilled',
               'nexusKills',
               'nexusLost',
               'nexusTakedowns',
               'objectivesStolen',
               'objectivesStolenAssists',
               'participantId',
               'pentaKills',
               'quadraKills',
               'riotIdTagline',
               'skillshotsHit',
               'takedownsInAlcove',
               'scuttleCrabKills',
               'enemyJungleMonsterKills',
               'epicMonsterKillsNearEnemyJungler',
               'epicMonsterKillsWithin30SecondsOfSpawn',
               'epicMonsterSteals',
               'epicMonsterStolenWithoutSmite',
               'flawlessAces',
               'getTakedownsInAllLanesEarlyJungleAsLaner',
               'elderDragonMultikills',
               'goldPerMinute',
               'hadOpenNexus',
               'immobilizeAndKillWithAlly',
               'initialBuffCount',
               'initialCrabCount',
               'junglerTakedownsNearDamagedEpicMonster',
               'kTurretsDestroyedBeforePlatesFall',
               'killAfterHiddenWithAlly',
               'hadAfkTeammate',
               'elderDragonKillsWithOpposingSoul',
               'earliestDragonTakedown',
               'earliestBaron',
               'baronKills',
               'bountyLevel',
               '12AssistStreakCount',
               'abilityUses',
               'acesBefore15Minutes',
               'baronTakedowns',
               'blastConeOppositeOpponentCount',
               'bountyGold',
               'buffsStolen',
               'completeSupportQuestInTime',
               'controlWardsPlaced',
               'damageTakenOnTeamPercentage',
               'dancedWithRiftHerald',
               'deathsByEnemyChamps',
               'dodgeSkillShotsSmallWindow',
               'doubleAces',
               'dragonTakedowns',
               'killedChampTookFullTeamDamageSurvived',
               'killsNearEnemyTurret',
               'visionWardsBoughtInGame',
               'killsOnRecentlyHealedByAramPack',
               'poroExplosions',
               'perfectGame',
               'perfectDragonSoulsTaken',
               'outnumberedNexusKill',
               'outnumberedKills',
               'lostAnInhibitor',
               'multiTurretRiftHeraldCount',
               'maxCsAdvantageOnLaneOpponent',
               'outerTurretExecutesBefore10Minutes',
               'mejaisFullStackInTime',
               'maxLevelLeadLaneOpponent',
               'multikillsAfterAggressiveFlash',
               'multikills',
               'killsOnOtherLanesEarlyJungleAsLaner',
               'maxKillDeficit',
               'quickCleanse',
               'multiKillOneSpell',
               'legendaryCount',
               'killsUnderOwnTurret',
               'laneMinionsFirst10Minutes',
               'quickSoloKills',
               'riftHeraldTakedowns',
               'killsWithHelpFromEpicMonster',
               'quickFirstTurret',
               'saveAllyFromDeath',
               'totalUnitsHealed',
               'damageDealtToObjectives',
               'shortestTimeToAceFromFirstTakedown',
               'skillshotsDodged',
               'pickKillWithAlly',
               'earliestElderDragon',
               'laningPhaseGoldExpAdvantage',
               'inhibitorsLost',
               'turretTakedowns',
               'killParticipation',
               'fasterSupportQuestCompletion',
               'fullTeamTakedown',
               'firstTurretKilledTime',
               'physicalDamageDealtToChampions'
               ]



LOL_DIVISIONS = {'Hierro IV': 0, 'Hierro III': 1, 'Hierro II': 2, 'Hierro I': 3, 'Bronce IV': 4, 'Bronce III': 5,
                 'Bronce II': 6, 'Bronce I': 7, 'Plata IV': 8, 'Plata III': 9, 'Plata II': 10, 'Plata I': 11,
                 'Oro IV': 12, 'Oro III': 13, 'Oro II': 14, 'Oro I': 15, 'Platino IV': 16, 'Platino III': 17,
                 'Platino II': 18, 'Platino I': 19, 'Diamante IV': 20, 'Diamante III': 21, 'Diamante II': 22,
                 'Diamante I': 23, 'Master': 24, 'GrandMaster': 25, 'Challenger': 26}

NUMBER_OF_GAMES = 20
