# -*- coding: utf-8 -*-
"""trabajogrupo3SAT_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Apg6obad-aonBfvVz1taibvz33p5bH5Z
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_excel('/content/drive/MyDrive/saturday ai/España/DatabaseAcciona.xlsx',sheet_name=1)

# Describir el dataset
num_observations = df.shape[0]
num_variables = df.shape[1]
variables = df.columns.tolist()

# Identificar variables numéricas y categóricas
numeric_vars = df.select_dtypes(include=['number']).columns.tolist()
categorical_vars = df.select_dtypes(include=['object']).columns.tolist()

# Mostrar la descripción del dataset
print('Número de observaciones:', num_observations)
print('Número de variables:', num_variables)
print('Variables:', variables)
print('Variables numéricas:', numeric_vars)
print('Variables categóricas:', categorical_vars)

# Mostrar las primeras filas del dataset
print(df.head())

# Análisis descriptivo básico
descriptive_stats = df.describe(include='all').transpose()
descriptive_stats

# Porcentaje de valores faltantes por columna
missing_values_percentage = df.isnull().mean() * 100
missing_values_percentage

# Importar pandas y tqdm
import pandas as pd
from tqdm import tqdm

# Configurar tqdm para trabajar con pandas
tqdm.pandas()

# Suponiendo que 'df' es tu DataFrame, 'numeric_cols' son las columnas numéricas y 'non_numeric_cols' son las no numéricas
numeric_cols = ['ID', 'codigo', 'year', 'AñoConst', 'AñoServ', 'A0', 'AA2', 'AA',
       'yr_construccion', 'yr_operacion', 'yr_serv', 'control', 't_group_cons',
       't_group_oper', 'control_otrosrenovables', 'CODAUTO', 'CPRO',
       'comarca_num', 'CODAUTO_num', 'CPRO_num', 'poblacion', '_0_14_',
       '_15_29_', '_30_44_', '_45_64_', 'mas65_', 'rentaBruta',
       'rentaDisponible', 'declaraciones', 'paro', 'afiliadosSS', 'MW',
       'MW_total_cons', 'MW_total_oper', 'MW_otrosrenovables', 'lpoblacion',
       'l_0_14_', 'l_15_29_', 'l_30_44_', 'l_45_64_', 'l_mas65_',
       'lrentaBruta', 'lparo', 'lafiliados']

non_numeric_cols = ['nombre_municipio', 'provincia', 'comarca', 'localizacion',
       'centro_produccion', 'pais', 'CCAA_Acciona', 'provincia_acciona',
       'localizacion_completa', 'tecnologia']

# Imputar valores NA en columnas numéricas con el valor 0
df[numeric_cols] = df[numeric_cols].progress_apply(lambda x: x.fillna(0), axis=0)

# Imputar valores NA en columnas no numéricas con el valor 0
df[non_numeric_cols] = df[non_numeric_cols].progress_apply(lambda x: x.fillna(0), axis=0)

# Verificar que no queden valores NA
after_na_counts = df.isna().sum()
print('Valores NA después de la imputación:')
print(after_na_counts)

# Variables socioeconómicas a analizar
socioeconomic_vars = ['rentaBruta','poblacion' 'rentaDisponible', 'paro', 'afiliadosSS']

# Filtrar datos por grupos de control
acciona_renovables = df[df['control'] == 0]
otros_renovables = df[df['control'] == 1]
sin_renovables = df[df['control'] == 2]

# Calcular medias para cada grupo
mean_acciona = acciona_renovables[socioeconomic_vars].mean()
mean_sin = sin_renovables[socioeconomic_vars].mean()

# Calcular la diferencia porcentual
percentage_diff = ((mean_acciona - mean_sin) / mean_sin) * 100

percentage_diff

import matplotlib.pyplot as plt

# Crear el gráfico de barras
percentage_diff.plot(kind='bar', figsize=(10, 6), color=['skyblue', 'lightgreen', 'salmon', 'orange', 'purple'])

# Añadir títulos y etiquetas
plt.title('Diferencia Porcentual en Variables Socioeconómicas entre Municipios con y sin Renovables de Acciona')
plt.ylabel('Diferencia Porcentual (%)')
plt.xlabel('Variables Socioeconómicas')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Mostrar el gráfico
plt.show()

# Definir las columnas numéricas
numeric_cols = ['ID', 'codigo', 'year', 'AñoConst', 'AñoServ', 'A0', 'AA2', 'AA',
       'yr_construccion', 'yr_operacion', 'yr_serv', 'control', 't_group_cons',
       't_group_oper', 'control_otrosrenovables', 'CODAUTO', 'CPRO',
       'comarca_num', 'CODAUTO_num', 'CPRO_num', 'poblacion', '_0_14_',
       '_15_29_', '_30_44_', '_45_64_', 'mas65_', 'rentaBruta',
       'rentaDisponible', 'declaraciones', 'paro', 'afiliadosSS', 'MW',
       'MW_total_cons', 'MW_total_oper', 'MW_otrosrenovables', 'lpoblacion',
       'l_0_14_', 'l_15_29_', 'l_30_44_', 'l_45_64_', 'l_mas65_',
       'lrentaBruta', 'lparo', 'lafiliados']

# Calcular la matriz de correlación solo para las columnas numéricas
correlacion = df[numeric_cols].corr()

# Crear un mapa de calor para la matriz de correlación
plt.figure(figsize=(20, 15))
sns.heatmap(correlacion, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("Matriz de Correlación")
plt.show()

# Variables socioeconómicas a analizar
socioeconomic_vars = ['poblacion', 'rentaBruta', 'rentaDisponible', 'paro', 'afiliadosSS']

# Calcular estadísticas descriptivas para cada grupo de control
descriptive_stats = df.groupby('control')[socioeconomic_vars].describe()
print(descriptive_stats)

"""haciendo un analisis descriptivo:
Los municipios con activos renovables, tanto de Acciona como de otras empresas, tienden a tener poblaciones más grandes que los municipios sin activos renovables.
Los municipios con activos renovables NO Acciona tienen, en promedio, las poblaciones más grandes.
La mediana y los percentiles sugieren que en general, aunque algunos municipios tienen poblaciones muy grandes, la mayoría de los municipios tienen poblaciones más pequeñas, especialmente los que no tienen activos renovables.


Las diferencias en la renta bruta promedio son relativamente pequeñas entre los tres tipos de municipios.
Los municipios con activos renovables de Acciona tienen un ingreso promedio ligeramente mayor que los otros dos grupos.


Los municipios con activos renovables NO Acciona tienen los valores más altos de desempleo registrado.
El desempleo parece ser un problema más grave en municipios con activos renovables NO Acciona en comparación con los otros dos grupos.

Los municipios con activos renovables NO Acciona tienen el mayor promedio de afiliados a la seguridad social, seguido por los municipios con activos renovables de Acciona.
Los municipios sin activos renovables tienen, en promedio, la menor cantidad de afiliados a la seguridad social.
Las diferencias en la mediana y los percentiles indican una mayor concentración de afiliados en los municipios con activos renovables, particularmente los NO Acciona.

Población: Los municipios con activos renovables, especialmente los NO Acciona, tienden a ser más grandes en términos de población.
Renta Bruta: Las diferencias en ingresos son menores, aunque los municipios con activos de Acciona tienen una ligera ventaja.
Paro: El desempleo es notablemente más alto en municipios con activos renovables NO Acciona.
Afiliados a la Seguridad Social: Los municipios con activos renovables NO Acciona tienen un mayor número de afiliados, indicando posiblemente una mayor actividad económica o mejor acceso a empleos formales.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Comparar la renta bruta per cápita entre los grupos
plt.figure(figsize=(10, 6))
sns.boxplot(x='control', y='rentaBruta', data=df)
plt.title('Comparación de Renta Bruta per Cápita entre Grupos')
plt.show()

# Comparar el número de parados entre los grupos
plt.figure(figsize=(10, 6))
sns.boxplot(x='control', y='paro', data=df)
plt.title('Comparación del Número de Parados entre Grupos')
plt.show()

# Comparar el número de afiliados a la Seguridad Social entre los grupos
plt.figure(figsize=(10, 6))
sns.boxplot(x='control', y='afiliadosSS', data=df)
plt.title('Comparación del Número de Afiliados a la Seguridad Social entre Grupos')
plt.show()

# Comparar el número de poblacion entre los grupos
plt.figure(figsize=(10, 6))
sns.boxplot(x='control', y='poblacion', data=df)
plt.title('Comparación del Número de Poblacion entre Grupos')
plt.show()

# Comparar las medias de las variables socioeconómicas entre los grupos usando ANOVA
from scipy.stats import f_oneway

# Variables a comparar
variables = ['rentaBruta', 'poblacion', 'paro', 'afiliadosSS']

# Realizar ANOVA para cada variable
for var in variables:
    group0 = df[df['control'] == 0][var]
    group1 = df[df['control'] == 1][var]
    group2 = df[df['control'] == 2][var]

    anova_result = f_oneway(group0, group1, group2)
    print(f"ANOVA result for {var}: F-value = {anova_result.statistic}, p-value = {anova_result.pvalue}")

"""Interpretación de los Resultados del ANOVA
El análisis de varianza (ANOVA) se ha utilizado para comparar las medias de varias variables socioeconómicas entre los tres grupos de municipios definidos por la variable control. Aquí están los resultados y su interpretación:

ANOVA para rentaBruta
F-value: 7.398704110893988
p-value: 0.0006122245626318528
Interpretación:

Un p-value menor a 0.05 indica que hay una diferencia significativa en la renta bruta promedio entre los tres grupos de municipios.
Dado que el p-value es muy pequeño (0.0006), podemos rechazar la hipótesis nula de que las medias de renta bruta son iguales en todos los grupos, sugiriendo que la presencia y el tipo de activo renovable influyen en la renta bruta de los municipios.
ANOVA para poblacion
F-value: 1690.779039174628
p-value: 0.0
Interpretación:

Un p-value de 0.0 indica una diferencia extremadamente significativa en la población promedio entre los tres grupos de municipios.
La alta F-value y el p-value extremadamente bajo sugieren que la presencia y el tipo de activo renovable están fuertemente asociados con diferencias en la población de los municipios.
ANOVA para paro
F-value: 1674.9529748308873
p-value: 0.0
Interpretación:

Al igual que con la población, un p-value de 0.0 indica una diferencia extremadamente significativa en el desempleo entre los tres grupos de municipios.
Esto sugiere que la presencia y el tipo de activo renovable tienen un fuerte impacto en los niveles de desempleo en los municipios.
ANOVA para afiliadosSS
F-value: 894.6722568785225
p-value: 0.0
Interpretación:

El p-value de 0.0 indica una diferencia extremadamente significativa en el número de afiliados a la seguridad social entre los tres grupos de municipios.
Las diferencias en el número de afiliados a la seguridad social también están fuertemente asociadas con la presencia y el tipo de activo renovable.
Resumen General
Los resultados del ANOVA sugieren que hay diferencias significativas en las variables socioeconómicas (rentaBruta, poblacion, paro, afiliadosSS) entre los tres grupos de municipios definidos por la variable control. En particular:

Renta Bruta: Existe una diferencia significativa en la renta bruta entre los municipios con activos renovables de Acciona, con activos renovables NO Acciona, y sin activos renovables.
Población: Los municipios difieren significativamente en tamaño de población según el tipo de activo renovable presente.
Paro: El desempleo varía significativamente entre los grupos de municipios, lo que sugiere que el tipo de activo renovable tiene un impacto en los niveles de desempleo.
Afiliados a la Seguridad Social: El número de afiliados a la seguridad social también varía significativamente, indicando diferencias en la actividad económica formal entre los municipios.
Estos hallazgos respaldan la idea de que la presencia y el tipo de activos renovables tienen un impacto significativo en diversos aspectos socioeconómicos de los municipios.
"""

# Variables socioeconómicas a analizar
socioeconomic_vars = ['rentaBruta', 'poblacion', 'paro', 'afiliadosSS']

# Filtrar datos por grupos de control
acciona_renovables = df[df['control'] == 0]
otros_renovables = df[df['control'] == 1]
sin_renovables = df[df['control'] == 2]

# Calcular medias para cada grupo
mean_acciona = acciona_renovables[socioeconomic_vars].mean()
mean_sin = sin_renovables[socioeconomic_vars].mean()

# Calcular la diferencia porcentual
percentage_diff = ((mean_acciona - mean_sin) / mean_sin) * 100

percentage_diff

"""rentaBruta       4.198981
poblacion      199.268847
paro           200.161330
afiliadosSS    253.759146

Interpretación
Renta Bruta:

Los municipios con activos renovables de Acciona tienen una renta bruta promedio un 4.20% mayor que los municipios sin activos renovables.
Aunque la diferencia es relativamente pequeña, es significativa, como se indicó en el análisis ANOVA.
Población:

La población en los municipios con activos renovables de Acciona es un 199.27% mayor que en los municipios sin activos renovables.
Esta es una diferencia muy grande, lo que sugiere que los municipios con activos renovables de Acciona tienden a ser significativamente más grandes en términos de población.
Paro:

El paro en los municipios con activos renovables de Acciona es un 200.16% mayor que en los municipios sin activos renovables.
Esta diferencia notable podría estar relacionada con la estructura del mercado laboral y la economía en estos municipios.
Afiliados a la Seguridad Social:

El número de afiliados a la seguridad social en los municipios con activos renovables de Acciona es un 253.76% mayor que en los municipios sin activos renovables.
Esta diferencia sugiere una mayor actividad económica formal y una mayor tasa de empleo en los municipios con activos renovables de Acciona.
Conclusiones
Efecto Positivo en la Renta Bruta: Los municipios con activos renovables de Acciona muestran una renta bruta ligeramente mayor, lo cual es un indicador positivo aunque no drástico.
Impacto Significativo en la Población y el Empleo: Las diferencias marcadas en la población y el número de afiliados a la seguridad social indican que los activos renovables de Acciona pueden estar asociados con un mayor desarrollo económico y demográfico.
Mayor Paro en Municipios con Activos Renovables de Acciona: La alta diferencia en el paro podría requerir un análisis más detallado para entender las dinámicas laborales en estos municipios.
Estos resultados sugieren que los activos renovables de Acciona tienen un impacto notable en varios aspectos socioeconómicos, especialmente en términos de población y empleo.
"""

import matplotlib.pyplot as plt

# Crear el gráfico de barras
percentage_diff.plot(kind='bar', figsize=(10, 6), color=['skyblue', 'lightgreen', 'salmon', 'orange', 'purple'])

# Añadir títulos y etiquetas
plt.title('Diferencia Porcentual en Variables Socioeconómicas entre Municipios con acciona y sin Renovables')
plt.ylabel('Diferencia Porcentual (%)')
plt.xlabel('Variables Socioeconómicas')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Mostrar el gráfico
plt.show()

# Variables socioeconómicas a analizar
socioeconomic_vars = ['rentaBruta','poblacion', 'paro', 'afiliadosSS']

# Filtrar datos por grupos de control
acciona_renovables = df[df['control'] == 0]
otros_renovables = df[df['control'] == 1]
sin_renovables = df[df['control'] == 2]

# Calcular medias para cada grupo
mean_acciona = acciona_renovables[socioeconomic_vars].mean()
mean_otros_renovables = otros_renovables[socioeconomic_vars].mean()

# Calcular la diferencia porcentual
percentage_diff = ((mean_acciona - mean_otros_renovables) / mean_otros_renovables) * 100

percentage_diff

"""Interpretación
Renta Bruta:

Los municipios con activos renovables de Acciona tienen una renta bruta promedio un 0.59% mayor que los municipios con otros activos renovables.
La diferencia es pequeña, indicando que la renta bruta es similar entre estos dos grupos de municipios.
Población:

La población en los municipios con activos renovables de Acciona es un 57.33% menor que en los municipios con otros activos renovables.
Esta diferencia significativa sugiere que los municipios con activos renovables de Acciona tienden a ser más pequeños en términos de población en comparación con aquellos con otros activos renovables.
Paro:

El paro en los municipios con activos renovables de Acciona es un 57.93% menor que en los municipios con otros activos renovables.
Esta notable diferencia podría indicar mejores condiciones laborales o una menor tasa de desempleo en los municipios con activos renovables de Acciona.
Afiliados a la Seguridad Social:

El número de afiliados a la seguridad social en los municipios con activos renovables de Acciona es un 63.77% menor que en los municipios con otros activos renovables.
Esta diferencia sugiere una menor actividad económica formal y una menor tasa de empleo en los municipios con activos renovables de Acciona en comparación con aquellos con otros activos renovables.
Conclusiones
Renta Bruta Similar: La renta bruta entre los municipios con activos renovables de Acciona y los de otros renovables es muy similar, con una diferencia mínima.
Menor Población y Empleo en Municipios con Activos Renovables de Acciona: Los municipios con activos renovables de Acciona tienden a tener una población y un empleo significativamente menores en comparación con los municipios con otros activos renovables.
Menor Paro en Municipios con Activos Renovables de Acciona: A pesar de la menor población y empleo, los municipios con activos renovables de Acciona muestran una menor tasa de paro, lo cual es un indicador positivo en términos de empleo.
"""

import matplotlib.pyplot as plt

# Crear el gráfico de barras
percentage_diff.plot(kind='bar', figsize=(10, 6), color=['skyblue', 'lightgreen', 'salmon', 'orange', 'purple'])

# Añadir títulos y etiquetas
plt.title('Diferencia Porcentual en Variables Socioeconómicas entre Municipios con acciona y otros Renovables')
plt.ylabel('Diferencia Porcentual (%)')
plt.xlabel('Variables Socioeconómicas')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Mostrar el gráfico
plt.show()

import statsmodels.api as sm

# Seleccionamos las variables relevantes
data = df[['paro', 'rentaBruta', 'poblacion', 'afiliadosSS', 'control']]

# Crear matrices de diseño para el modelo de regresión
X = sm.add_constant(data['control'])  # Matriz de diseño (incluye término constante)

# Crear y ajustar modelos de regresión para cada variable dependiente
model_paro = sm.OLS(data['paro'], X).fit()
model_afiliadosSS = sm.OLS(data['afiliadosSS'], X).fit()
model_rentaBruta = sm.OLS(data['rentaBruta'], X).fit()
model_poblacion = sm.OLS(data['poblacion'], X).fit()

# Imprimir los resultados
print("Resultados para Paro:")
print(model_paro.summary())
print("\nResultados para Afiliados a la Seguridad Social:")
print(model_afiliadosSS.summary())
print("\nResultados para rentaBruta:")
print(model_rentaBruta.summary())
print("\nResultados para población:")
print(model_poblacion.summary())

"""Conclusiones:
Paro:
El modelo de regresión lineal muestra que el índice de control está significativamente relacionado con la tasa de paro (p < 0.001).
Para cada unidad de aumento en el índice de control, la tasa de paro disminuye en promedio en 666.45 personas por cada mil habitantes.
El modelo tiene un bajo poder explicativo (R² = 0.011), lo que indica que solo el 1.1% de la variabilidad en la tasa de paro se explica por el índice de control.
Afiliados a la Seguridad Social:
Hay una relación significativa entre el índice de control y el número de afiliados a la Seguridad Social (p < 0.001).
Para cada unidad de aumento en el índice de control, el número de afiliados a la Seguridad Social disminuye en promedio en 3,973 personas.
El modelo tiene un poder explicativo muy bajo (R² = 0.006), lo que indica que solo el 0.6% de la variabilidad en el número de afiliados se explica por el índice de control.
Renta Bruta:
Existe una relación significativa entre el índice de control y la renta bruta (p < 0.001).
Por cada unidad de aumento en el índice de control, la renta bruta disminuye en promedio en 191.22 unidades monetarias.
El modelo tiene un poder explicativo muy bajo (R² = 0.000), lo que indica que la variabilidad en la renta bruta apenas se ve afectada por el índice de control.
Población:
Hay una relación significativa entre el índice de control y la población (p < 0.001).
Para cada unidad de aumento en el índice de control, la población disminuye en promedio en 11,310 personas.
El modelo tiene un bajo poder explicativo (R² = 0.011), lo que indica que solo el 1.1% de la variabilidad en la población se explica por el índice de control.
Estos resultados sugieren que el índice de control tiene un impacto significativo pero relativamente bajo en las variables socioeconómicas analizadas. Sin embargo, el poder explicativo de los modelos es bastante bajo, lo que sugiere que otros factores no considerados en el modelo podrían estar influyendo en estas variables.
"""

# Importar librerías necesarias
import pandas as pd
from scipy.stats import ttest_ind

# Separar los municipios con y sin activos renovables
municipios_con = df[df['control'] == 1]
municipios_sin = df[df['control'] == 0]

# Calcular la media de población por grupo de edad para cada grupo
media_por_edad_con = municipios_con[['poblacion', '_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()
media_por_edad_sin = municipios_sin[['poblacion', '_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()

# Realizar una prueba t para la diferencia de medias
t_stat, p_valor = ttest_ind(municipios_con['poblacion'], municipios_sin['poblacion'], equal_var=False)

print("Media de población por grupo de edad en municipios con activos renovables:\n", media_por_edad_con)
print("\nMedia de población por grupo de edad en municipios sin activos renovables:\n", media_por_edad_sin)
print("\nPrueba t para la diferencia de medias:")
print("p-valor =", p_valor)

import pandas as pd
import matplotlib.pyplot as plt

# Filtrar datos para población antes de la instalación de activos renovables
poblacion_pre_renovables = df[df['control'] == 2][['_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()

# Filtrar datos para población después de la instalación de activos renovables
poblacion_post_renovables = df[df['control'] == 0][['_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()

# Graficar
plt.figure(figsize=(10, 6))

# Población antes de la instalación de activos renovables
plt.plot(poblacion_pre_renovables.index, poblacion_pre_renovables, label='Antes de Renovables', marker='o')

# Población después de la instalación de activos renovables
plt.plot(poblacion_post_renovables.index, poblacion_post_renovables, label='Después de Renovables', marker='o')

# Etiquetas y título
plt.xlabel('Grupo de Edad')
plt.ylabel('Población')
plt.title('Evolución de la Población por Grupo de Edad')
plt.legend()

# Mostrar la gráfica
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# Filtrar datos para población antes y después de la instalación de activos renovables
poblacion_pre_renovables = df[df['control'] == 2][['_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()
poblacion_post_renovables = df[df['control'] == 0][['_0_14_', '_15_29_', '_30_44_', '_45_64_', 'mas65_']].mean()

# Filtrar datos de paro antes y después
paro_pre_renovables = df[df['control'] == 2]['paro'].mean()
paro_post_renovables = df[df['control'] == 0]['paro'].mean()

# Filtrar datos de renta bruta antes y después
renta_bruta_pre_renovables = df[df['control'] == 2]['rentaBruta'].mean()
renta_bruta_post_renovables = df[df['control'] == 0]['rentaBruta'].mean()

# Filtrar datos de afiliados a la Seguridad Social antes y después
afiliadosSS_pre_renovables = df[df['control'] == 2]['afiliadosSS'].mean()
afiliadosSS_post_renovables = df[df['control'] == 0]['afiliadosSS'].mean()

# Graficar
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Población antes y después
axes[0, 0].plot(poblacion_pre_renovables.index, poblacion_pre_renovables, label='Antes de Renovables', marker='o')
axes[0, 0].plot(poblacion_post_renovables.index, poblacion_post_renovables, label='Después de Renovables', marker='o')
axes[0, 0].set_title('Evolución de la Población por Grupo de Edad')
axes[0, 0].set_xlabel('Grupo de Edad')
axes[0, 0].set_ylabel('Población')
axes[0, 0].legend()

# Paro antes y después
axes[0, 1].bar(['Antes de Renovables', 'Después de Renovables'], [paro_pre_renovables, paro_post_renovables], color=['blue', 'orange'])
axes[0, 1].set_title('Tasa de Paro')
axes[0, 1].set_ylabel('Paro')

# Renta Bruta antes y después
axes[1, 0].bar(['Antes de Renovables', 'Después de Renovables'], [renta_bruta_pre_renovables, renta_bruta_post_renovables], color=['blue', 'orange'])
axes[1, 0].set_title('Renta Bruta')
axes[1, 0].set_ylabel('Renta Bruta')

# Afiliados a la Seguridad Social antes y después
axes[1, 1].bar(['Antes de Renovables', 'Después de Renovables'], [afiliadosSS_pre_renovables, afiliadosSS_post_renovables], color=['blue', 'orange'])
axes[1, 1].set_title('Afiliados a la Seguridad Social')
axes[1, 1].set_ylabel('Afiliados a la Seguridad Social')

# Ajustar diseño
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


# Calcular la renta bruta media por año para municipios con y sin activos renovables
renta_bruta_pre = df[df['t_group_oper'] == 0].groupby('year')['rentaBruta'].mean()
renta_bruta_post = df[df['t_group_oper'] == 1].groupby('year')['rentaBruta'].mean()

# Graficar
plt.figure(figsize=(10, 6))

# Graficar la renta bruta antes y después
plt.plot(renta_bruta_pre.index, renta_bruta_pre.values, marker='o', label='Antes de Renovables')
plt.plot(renta_bruta_post.index, renta_bruta_post.values, marker='o', label='Después de Renovables')

plt.title('Impacto de Renovables de Acciona en la Renta Bruta por Año')
plt.xlabel('Año')
plt.ylabel('Renta Bruta')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Calcular la tasa de paro media por año para municipios con y sin activos renovables
tasa_paro_pre = df[df['t_group_oper'] == 0].groupby('year')['paro'].mean()
tasa_paro_post = df[df['t_group_oper'] == 1].groupby('year')['paro'].mean()

# Graficar
plt.figure(figsize=(10, 6))
plt.plot(tasa_paro_pre.index, tasa_paro_pre.values, marker='o', label='Antes de Renovables')
plt.plot(tasa_paro_post.index, tasa_paro_post.values, marker='o', label='Después de Renovables')
plt.title('Impacto de Renovables de Acciona en la Tasa de Paro por Año')
plt.xlabel('Año')
plt.ylabel('Tasa de Paro (%)')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Calcular la renta disponible media por año para municipios con y sin activos renovables
renta_disponible_pre = df[df['t_group_oper'] == 0].groupby('year')['rentaDisponible'].mean()
renta_disponible_post = df[df['t_group_oper'] == 1].groupby('year')['rentaDisponible'].mean()

# Graficar
plt.figure(figsize=(10, 6))
plt.plot(renta_disponible_pre.index, renta_disponible_pre.values, marker='o', label='Antes de Renovables')
plt.plot(renta_disponible_post.index, renta_disponible_post.values, marker='o', label='Después de Renovables')
plt.title('Impacto de Renovables de Acciona en la Renta Disponible por Año')
plt.xlabel('Año')
plt.ylabel('Renta Disponible')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Calcular la afiliación a la Seguridad Social media por año para municipios con y sin activos renovables
afiliados_pre = df[df['t_group_oper'] == 0].groupby('year')['afiliadosSS'].mean()
afiliados_post = df[df['t_group_oper'] == 1].groupby('year')['afiliadosSS'].mean()

# Graficar
plt.figure(figsize=(10, 6))
plt.plot(afiliados_pre.index, afiliados_pre.values, marker='o', label='Antes de Renovables')
plt.plot(afiliados_post.index, afiliados_post.values, marker='o', label='Después de Renovables')
plt.xlabel('Año')
plt.ylabel('afiliadosSS')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Simulated dataset for demonstration purposes
data = {
    'year': list(range(2000, 2023)),
    't_group_oper': [0]*10 + [1]*13,
    'rentaBruta': [15000, 15200, 15400, 15500, 15700, 16000, 16200, 16300, 16500, 16600, 16700, 16800, 17000, 17200, 17500, 17800, 18000, 18300, 18600, 18900, 19200, 19500, 19800]
}

df = pd.DataFrame(data)

# Filter data
pre_intervencion = df[df['t_group_oper'] == 0].groupby('year')['rentaBruta'].mean()
post_intervencion = df[df['t_group_oper'] == 1].groupby('year')['rentaBruta'].mean()

# Plot
plt.figure(figsize=(12, 6))
plt.plot(pre_intervencion.index, pre_intervencion.values, label='Antes de Renovables', marker='o')
plt.plot(post_intervencion.index, post_intervencion.values, label='Después de Renovables', marker='o')
plt.axvline(x=min(df[df['t_group_oper'] == 1]['year']), color='r', linestyle='--', label='Inicio de Operación de Renovables')

plt.title('Evolución de la Renta Bruta Antes y Después de la Instalación de Renovables de Acciona')
plt.xlabel('Año')
plt.ylabel('Renta Bruta')
plt.legend()
plt.grid(True)
plt.show()

"""analisis solo asturias"""

from scipy.stats import f_oneway

# Filtrar los datos por los tres grupos de control
acciona_asturias = df[(df['provincia'] == 'Asturias') & (df['control'] == 0)]
no_acciona_asturias = df[(df['provincia'] == 'Asturias') & (df['control'] == 1)]
sin_renovables_asturias = df[(df['provincia'] == 'Asturias') & (df['control'] == 2)]

# Extraer las variables de interés
renta_bruta_acciona = acciona_asturias['rentaBruta'].dropna()
renta_bruta_no_acciona = no_acciona_asturias['rentaBruta'].dropna()
renta_bruta_sin_renovables = sin_renovables_asturias['rentaBruta'].dropna()

paro_acciona = acciona_asturias['paro'].dropna()
paro_no_acciona = no_acciona_asturias['paro'].dropna()
paro_sin_renovables = sin_renovables_asturias['paro'].dropna()

afiliadosSS_acciona = acciona_asturias['afiliadosSS'].dropna()
afiliadosSS_no_acciona = no_acciona_asturias['afiliadosSS'].dropna()
afiliadosSS_sin_renovables = sin_renovables_asturias['afiliadosSS'].dropna()

poblacion_acciona = acciona_asturias['poblacion'].dropna()
poblacion_no_acciona = no_acciona_asturias['poblacion'].dropna()
poblacion_sin_renovables = sin_renovables_asturias['poblacion'].dropna()


# ANOVA para renta bruta
renta_bruta_anova = f_oneway(renta_bruta_acciona, renta_bruta_no_acciona, renta_bruta_sin_renovables)
print('Resultados del ANOVA para renta bruta en Asturias:')
print(renta_bruta_anova)

# ANOVA para paro
paro_anova = f_oneway(paro_acciona, paro_no_acciona, paro_sin_renovables)
print('Resultados del ANOVA para paro en Asturias:')
print(paro_anova)

# ANOVA para afiliados a la Seguridad Social
afiliadosSS_anova = f_oneway(afiliadosSS_acciona, afiliadosSS_no_acciona, afiliadosSS_sin_renovables)
print('Resultados del ANOVA para afiliados a la Seguridad Social en Asturias:')
print(afiliadosSS_anova)


# ANOVA para poblacion
poblacion_anova = f_oneway(poblacion_acciona, poblacion_no_acciona, poblacion_sin_renovables)
print('Resultados del ANOVA para poblacion en Asturias:')
print(poblacion_anova)

import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo
sns.set(style='whitegrid')

# Crear una figura con subplots
fig, axes = plt.subplots(4, 1, figsize=(12, 18))

# Gráfico para renta bruta
sns.boxplot(x='control', y='rentaBruta', data=df[df['provincia'] == 'Asturias'], ax=axes[0])
axes[0].set_title('Renta Bruta en Asturias por Grupo de Control')
axes[0].set_xlabel('Grupo de Control')
axes[0].set_ylabel('Renta Bruta')
axes[0].set_xticklabels(['Acciona', 'No Acciona', 'Sin Renovables'])

# Gráfico para paro
sns.boxplot(x='control', y='paro', data=df[df['provincia'] == 'Asturias'], ax=axes[1])
axes[1].set_title('Paro en Asturias por Grupo de Control')
axes[1].set_xlabel('Grupo de Control')
axes[1].set_ylabel('Paro')
axes[1].set_xticklabels(['Acciona', 'No Acciona', 'Sin Renovables'])

# Gráfico para afiliados a la Seguridad Social
sns.boxplot(x='control', y='afiliadosSS', data=df[df['provincia'] == 'Asturias'], ax=axes[2])
axes[2].set_title('Afiliados a la Seguridad Social en Asturias por Grupo de Control')
axes[2].set_xlabel('Grupo de Control')
axes[2].set_ylabel('Afiliados a la Seguridad Social')
axes[2].set_xticklabels(['Acciona', 'No Acciona', 'Sin Renovables'])

sns.boxplot(x='control', y='poblacion', data=df[df['provincia'] == 'Asturias'], ax=axes[3])
axes[3].set_title('Poblacion en Asturias por Grupo de Control')
axes[3].set_xlabel('Grupo de Control')
axes[3].set_ylabel('Poblacion')
axes[3].set_xticklabels(['Acciona', 'No Acciona', 'Sin Renovables'])

# Ajustar el layout
plt.tight_layout()

# Mostrar los gráficos
plt.show()